# Generated by Django 3.1.7 on 2021-03-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('jobrole', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=10)),
                ('it', models.BooleanField(default=False, verbose_name='IT')),
                ('cse', models.BooleanField(default=False, verbose_name='CSE')),
                ('ece', models.BooleanField(default=False, verbose_name='ECE')),
                ('mech', models.BooleanField(default=False, verbose_name='MECH')),
                ('eee', models.BooleanField(default=False, verbose_name='EEE')),
            ],
        ),
    ]
